# Generated by Django 3.1 on 2020-08-28 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudsandthreads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='Date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='price',
        ),
    ]
